vim.g.have_nerd_font = true

vim.o.number = true
vim.o.relativenumber = true
vim.o.wrap = false
vim.o.smartcase = true
vim.o.ignorecase = true
vim.o.expandtab = true
vim.o.autoindent = true
vim.o.smartindent = true
vim.o.termguicolors = true
vim.o.shiftwidth = 4
vim.o.tabstop = 4
vim.o.scrolloff = 4
vim.o.sidescrolloff = 4
vim.o.showtabline = 1
vim.o.laststatus = 3
vim.o.fillchars = "eob: "
vim.o.signcolumn = "yes"
